server:
  port: 9527

spring:
  application:
    name: cloud-geteway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates: #断言,路径相匹配的进行路由
            - Path=/payment/**

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/discovery/**

        - id: news_route
          uri: http://news.baidu.com/
          predicates:
            - Path=/guonei

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
