server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名字
  client:
    register-with-eureka: false #表识不向注册中心注册自己,默认为true
    fetch-registry: false #是否从EurekaServer抓取已有的注册信息，默认为true。表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka #设置与eureka server交互的地址 查询服务和注册服务都需要依赖这个地址


